name: "deploy_on_push"

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    name: "Deploy on Push"
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
      - name: deploy on push
        run: curl -X POST  -d {} ${{secrets.NETLIFY_BUILD_HOOK}}
