name: "deploy_on_push"

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: deploy on push
        run: curl -X POST  -d {} ${{secrets.NETLIFY_BUILD_HOOK}}
