name: Trigger Netlify Build
on:
  schedule:
    - cron: "*/1 * * * *" # every 15 mins
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{secrets.NETLIFY_BUILD_HOOK}}
